# Default values for service-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: captntuttle/ecs-service-broker
  tag: latest
  pullPolicy: IfNotPresent

#nameOverride: ""
#fullnameOverride: ""

registerBroker: true

service:
  type: ClusterIP
  nodeport:
    port: 30080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

broker:
  connectivity:
    namespace: "131118670375936839"
    management_endpoint: https://portal.ecstestdrive.com
    replication_group: ecstestdrivegeo
    username: 131118670375936839-admin
    password: ZWNmNzZiNjI0YTExODczYzJkZGVmNWU5NjQ4MzlkMjk=
    base_url: ""
    object_endpoint: https://object.ecstestdrive.com
  service:
    prefix: 131118670375936839-
    repository_endpoint: ""
    repository_user: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Basic auth credentials that can later be used to access this broker
basicAuth:
  ## DO NOT USE THIS DEFAULT VALUE IN PRODUCTION
  username: username
  ## DO NOT USE THIS DEFAULT VALUE IN PRODUCTION
  password: password

nodeSelector: {}

tolerations: []

affinity: {}
